name: Build and Release Binary

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and Upload
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build Linux Binary
      run: |
        GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o recon

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        files: recon
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
